### ISSUE TITLE
Eoside missing interaction with vscode

### ISSUE THREAD

**Issue by Adam-Kielkowski** [tokenika/eoside#1]
Hello,

I have got a problem with running eoside- simply, eoside does not interact with vscode. After succesfull installation, executing 'eoside.ps1' or 'code -n' inside eoside folder opens clean vscode without eoside page.

Steps what have been done (to reproduce):

installed eosio:
```
wget https://github.com/eosio/eos/releases/download/v1.4.4/eosio_1.4.4-1-ubuntu-18.04_amd64.deb
sudo apt install ./eosio_1.4.4-1-ubuntu-18.04_amd64.deb
```

installled newest clean vscode for linux from:
```
https://code.visualstudio.com/
```

Installed eoside:
```
Downloaded and unpacked this repo
chmod +x install.sh
./install.sh
```
No errors appeared during this process.

Is there anything else to do?

My specs:
OS Ubuntu 18.04.1 LTS
Python version 3.6.7
Pip version 9.0.1 
VScode version 1.29.1

any help would be appreciated.

**Comment by stefanzarembinski** [comment]
The eoside project is not published jet. Especially, it has never been tested with
OS Ubuntu, as we develop it with Windows + WSL. More, it is possible that the 
installer is not flawless jet.

We hope, we wil be ready in one month from now.
